title: Rachael's Radical Ramblings
author: Rachael Yoder
email: wayoder4@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog that follows my personal development as a programmer and where I post personal opinions without controversy
# social links
twitter_username: your-twitter-handle
github_username:  http://github.com/rachyoder

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
